[component]
structures = ["content_blocks"]
label = "Start"
description = "Start block"
icon = "flight_takeoff"
tags = []

[props]
preheading = "What we are"
heading = "We are dynamic team of creative people"
text = "We provide consulting services in the area of IFRS and management reporting, helping companies to reach their highest level. We optimize business processes, making them easier."
image_path = "/images/bg/home-7.jpg"

[props.button]
text = "Get started"
url = "/contact/"
