collections_config:
  pages:
    sort_options: 
      - key: title
      - key: title
        order: desc
    schemas:
      default:
        path: schemas/page.md
    _enabled_editors:
      - visual
  posts:
    sort_options: 
      - key: title
      - key: title
        order: desc
      - key: date
        label: Newest first
      - key: date
        order: desc
        label: Oldest first
    schemas:
      default:
        path: schemas/post.md
    _enabled_editors:
      - content
      - visual
    
    _inputs: 
      categories: 
        type: array
      categories[*]:
        type: text

_structures: 
  menu_items:
    values: 
      - label: "Link"
        icon: link
        value:
          _id: "link"
          name:
          url: 
          open_in_new_tab: false
      - label: "Drop down menu"
        icon: arrow_drop_down
        value: 
          _id: "drop_down_menu"
          label: 
          sub_menu_items: 

  sub_menu_items: 
    values:
      - label: "Link"
        icon: link
        value: 
          _id: "sub_menu_link"
          name:
          url: 
          open_in_new_tab: false
      - label: "Divider"
        icon: maximize
        description: "Straight line divider"
        value:
          _id: "sub_menu_divider"


_inputs:
  description:
    description: Text used for the SEO meta description tag
  favicon:
    type: image
  logo_dark: 
    type: image
  logo_light:
    type: image
  sub_menu_items: 
    type: array
    comment: Sub nav links which will appear in a dropdown menu when hovering over the parent label. If no sub menu items are present there will be no dropdown menu. 
    options:
      structures: _structures.sub_menu_items

  content:
    type: markdown
  icon:
    type: select
    options: 
      values:
        ti-wand: Wand
        ti-volume: Volume
        ti-user: User
        ti-unlock: Unlock
        ti-unlink: Unlink
        ti-trash: Trash
        ti-thought: Thought
        ti-target: Target
        ti-tag: Tag
        ti-tablet: Tablet
        ti-star: Star
        ti-spray: Spray
        ti-signal: Signal
        ti-shopping-cart: Shopping-Cart
        ti-shopping-cart-full: Shopping-Cart-Full
        ti-settings: Settings
        ti-search: Search
        ti-zoom-in: Zoom-In
        ti-zoom-out: Zoom-Out
        ti-cut: Cut
        ti-ruler: Ruler
        ti-ruler-pencil: Ruler-Pencil
        ti-ruler-alt: Ruler-Alt
        ti-bookmark: Bookmark
        ti-bookmark-alt: Bookmark-Alt
        ti-reload: Reload
        ti-plus: Plus
        ti-pin: Pin
        ti-pencil: Pencil
        ti-pencil-alt: Pencil-Alt
        ti-paint-roller: Paint-Roller
        ti-paint-bucket: Paint-Bucket
        ti-na: Na
        ti-mobile: Mobile
        ti-minus: Minus
        ti-medall: Medall
        ti-medall-alt: Medall-Alt
        ti-marker: Marker
        ti-marker-alt: Marker-Alt
        ti-arrow-up: Arrow-Up
        ti-arrow-right: Arrow-Right
        ti-arrow-left: Arrow-Left
        ti-arrow-down: Arrow-Down
        ti-lock: Lock
        ti-location-arrow: Location-Arrow
        ti-link: Link
        ti-layout: Layout
        ti-layers: Layers
        ti-layers-alt: Layers-Alt
        ti-key: Key
        ti-import: Import
        ti-image: Image
        ti-heart: Heart
        ti-heart-broken: Heart-Broken
        ti-hand-stop: Hand-Stop
        ti-hand-open: Hand-Open
        ti-hand-drag: Hand-Drag
        ti-folder: Folder
        ti-flag: Flag
        ti-flag-alt: Flag-Alt
        ti-flag-alt-2: Flag-Alt-2
        ti-eye: Eye
        ti-export: Export
        ti-exchange-vertical: Exchange-Vertical
        ti-desktop: Desktop
        ti-cup: Cup
        ti-crown: Crown
        ti-comments: Comments
        ti-comment: Comment
        ti-comment-alt: Comment-Alt
        ti-close: Close
        ti-clip: Clip
        ti-angle-up: Angle-Up
        ti-angle-right: Angle-Right
        ti-angle-left: Angle-Left
        ti-angle-down: Angle-Down
        ti-check: Check
        ti-check-box: Check-Box
        ti-camera: Camera
        ti-announcement: Announcement
        ti-brush: Brush
        ti-briefcase: Briefcase
        ti-bolt: Bolt
        ti-bolt-alt: Bolt-Alt
        ti-blackboard: Blackboard
        ti-bag: Bag
        ti-move: Move
        ti-arrows-vertical: Arrows-Vertical
        ti-arrows-horizontal: Arrows-Horizontal
        ti-fullscreen: Fullscreen
        ti-arrow-top-right: Arrow-Top-Right
        ti-arrow-top-left: Arrow-Top-Left
        ti-arrow-circle-up: Arrow-Circle-Up
        ti-arrow-circle-right: Arrow-Circle-Right
        ti-arrow-circle-left: Arrow-Circle-Left
        ti-arrow-circle-down: Arrow-Circle-Down
        ti-angle-double-up: Angle-Double-Up
        ti-angle-double-right: Angle-Double-Right
        ti-angle-double-left: Angle-Double-Left
        ti-angle-double-down: Angle-Double-Down
        ti-zip: Zip
        ti-world: World
        ti-wheelchair: Wheelchair
        ti-view-list: View-List
        ti-view-list-alt: View-List-Alt
        ti-view-grid: View-Grid
        ti-uppercase: Uppercase
        ti-upload: Upload
        ti-underline: Underline
        ti-truck: Truck
        ti-timer: Timer
        ti-ticket: Ticket
        ti-thumb-up: Thumb-Up
        ti-thumb-down: Thumb-Down
        ti-text: Text
        ti-stats-up: Stats-Up
        ti-stats-down: Stats-Down
        ti-split-v: Split-V
        ti-split-h: Split-H
        ti-smallcap: Smallcap
        ti-shine: Shine
        ti-shift-right: Shift-Right
        ti-shift-left: Shift-Left
        ti-shield: Shield
        ti-notepad: Notepad
        ti-server: Server
        ti-quote-right: Quote-Right
        ti-quote-left: Quote-Left
        ti-pulse: Pulse
        ti-printer: Printer
        ti-power-off: Power-Off
        ti-plug: Plug
        ti-pie-chart: Pie-Chart
        ti-paragraph: Paragraph
        ti-panel: Panel
        ti-package: Package
        ti-music: Music
        ti-music-alt: Music-Alt
        ti-mouse: Mouse
        ti-mouse-alt: Mouse-Alt
        ti-money: Money
        ti-microphone: Microphone
        ti-menu: Menu
        ti-menu-alt: Menu-Alt
        ti-map: Map
        ti-map-alt: Map-Alt
        ti-loop: Loop
        ti-location-pin: Location-Pin
        ti-list: List
        ti-light-bulb: Light-Bulb
        ti-Italic: Italic
        ti-info: Info
        ti-infinite: Infinite
        ti-id-badge: Id-Badge
        ti-hummer: Hummer
        ti-home: Home
        ti-help: Help
        ti-headphone: Headphone
        ti-harddrives: Harddrives
        ti-harddrive: Harddrive
        ti-gift: Gift
        ti-game: Game
        ti-filter: Filter
        ti-files: Files
        ti-file: File
        ti-eraser: Eraser
        ti-envelope: Envelope
        ti-download: Download
        ti-direction: Direction
        ti-direction-alt: Direction-Alt
        ti-dashboard: Dashboard
        ti-control-stop: Control-Stop
        ti-control-shuffle: Control-Shuffle
        ti-control-play: Control-Play
        ti-control-pause: Control-Pause
        ti-control-forward: Control-Forward
        ti-control-backward: Control-Backward
        ti-cloud: Cloud
        ti-cloud-up: Cloud-Up
        ti-cloud-down: Cloud-Down
        ti-clipboard: Clipboard
        ti-car: Car
        ti-calendar: Calendar
        ti-book: Book
        ti-bell: Bell
        ti-basketball: Basketball
        ti-bar-chart: Bar-Chart
        ti-bar-chart-alt: Bar-Chart-Alt
        ti-back-right: Back-Right
        ti-back-left: Back-Left
        ti-arrows-corner: Arrows-Corner
        ti-archive: Archive
        ti-anchor: Anchor
        ti-align-right: Align-Right
        ti-align-left: Align-Left
        ti-align-justify: Align-Justify
        ti-align-center: Align-Center
        ti-alert: Alert
        ti-alarm-clock: Alarm-Clock
        ti-agenda: Agenda
        ti-write: Write
        ti-window: Window
        ti-widgetized: Widgetized
        ti-widget: Widget
        ti-widget-alt: Widget-Alt
        ti-wallet: Wallet
        ti-video-clapper: Video-Clapper
        ti-video-camera: Video-Camera
        ti-vector: Vector
        ti-themify-logo: Themify-Logo
        ti-themify-favicon: Themify-Favicon
        ti-themify-favicon-alt: Themify-Favicon-Alt
        ti-support: Support
        ti-stamp: Stamp
        ti-split-v-alt: Split-V-Alt
        ti-slice: Slice
        ti-shortcode: Shortcode
        ti-shift-right-alt: Shift-Right-Alt
        ti-shift-left-alt: Shift-Left-Alt
        ti-ruler-alt-2: Ruler-Alt-2
        ti-receipt: Receipt
        ti-pin2: Pin2
        ti-pin-alt: Pin-Alt
        ti-pencil-alt2: Pencil-Alt2
        ti-palette: Palette
        ti-more: More
        ti-more-alt: More-Alt
        ti-microphone-alt: Microphone-Alt
        ti-magnet: Magnet
        ti-line-double: Line-Double
        ti-line-dotted: Line-Dotted
        ti-line-dashed: Line-Dashed
        ti-layout-width-full: Layout-Width-Full
        ti-layout-width-default: Layout-Width-Default
        ti-layout-width-default-alt: Layout-Width-Default-Alt
        ti-layout-tab: Layout-Tab
        ti-layout-tab-window: Layout-Tab-Window
        ti-layout-tab-v: Layout-Tab-V
        ti-layout-tab-min: Layout-Tab-Min
        ti-layout-slider: Layout-Slider
        ti-layout-slider-alt: Layout-Slider-Alt
        ti-layout-sidebar-right: Layout-Sidebar-Right
        ti-layout-sidebar-none: Layout-Sidebar-None
        ti-layout-sidebar-left: Layout-Sidebar-Left
        ti-layout-placeholder: Layout-Placeholder
        ti-layout-menu: Layout-Menu
        ti-layout-menu-v: Layout-Menu-V
        ti-layout-menu-separated: Layout-Menu-Separated
        ti-layout-menu-full: Layout-Menu-Full
        ti-layout-media-right-alt: Layout-Media-Right-Alt
        ti-layout-media-right: Layout-Media-Right
        ti-layout-media-overlay: Layout-Media-Overlay
        ti-layout-media-overlay-alt: Layout-Media-Overlay-Alt
        ti-layout-media-overlay-alt-2: Layout-Media-Overlay-Alt-2
        ti-layout-media-left-alt: Layout-Media-Left-Alt
        ti-layout-media-left: Layout-Media-Left
        ti-layout-media-center-alt: Layout-Media-Center-Alt
        ti-layout-media-center: Layout-Media-Center
        ti-layout-list-thumb: Layout-List-Thumb
        ti-layout-list-thumb-alt: Layout-List-Thumb-Alt
        ti-layout-list-post: Layout-List-Post
        ti-layout-list-large-image: Layout-List-Large-Image
        ti-layout-line-solid: Layout-Line-Solid
        ti-layout-grid4: Layout-Grid4
        ti-layout-grid3: Layout-Grid3
        ti-layout-grid2: Layout-Grid2
        ti-layout-grid2-thumb: Layout-Grid2-Thumb
        ti-layout-cta-right: Layout-Cta-Right
        ti-layout-cta-left: Layout-Cta-Left
        ti-layout-cta-center: Layout-Cta-Center
        ti-layout-cta-btn-right: Layout-Cta-Btn-Right
        ti-layout-cta-btn-left: Layout-Cta-Btn-Left
        ti-layout-column4: Layout-Column4
        ti-layout-column3: Layout-Column3
        ti-layout-column2: Layout-Column2
        ti-layout-accordion-separated: Layout-Accordion-Separated
        ti-layout-accordion-merged: Layout-Accordion-Merged
        ti-layout-accordion-list: Layout-Accordion-List
        ti-ink-pen: Ink-Pen
        ti-info-alt: Info-Alt
        ti-help-alt: Help-Alt
        ti-headphone-alt: Headphone-Alt
        ti-hand-point-up: Hand-Point-Up
        ti-hand-point-right: Hand-Point-Right
        ti-hand-point-left: Hand-Point-Left
        ti-hand-point-down: Hand-Point-Down
        ti-gallery: Gallery
        ti-face-smile: Face-Smile
        ti-face-sad: Face-Sad
        ti-credit-card: Credit-Card
        ti-control-skip-forward: Control-Skip-Forward
        ti-control-skip-backward: Control-Skip-Backward
        ti-control-record: Control-Record
        ti-control-eject: Control-Eject
        ti-comments-smiley: Comments-Smiley
        ti-brush-alt: Brush-Alt
        ti-youtube: Youtube
        ti-vimeo: Vimeo
        ti-twitter: Twitter
        ti-time: Time
        ti-tumblr: Tumblr
        ti-skype: Skype
        ti-share: Share
        ti-share-alt: Share-Alt
        ti-rocket: Rocket
        ti-pinterest: Pinterest
        ti-new-window: New-Window
        ti-microsoft: Microsoft
        ti-list-ol: List-Ol
        ti-linkedin: Linkedin
        ti-layout-sidebar-2: Layout-Sidebar-2
        ti-layout-grid4-alt: Layout-Grid4-Alt
        ti-layout-grid3-alt: Layout-Grid3-Alt
        ti-layout-grid2-alt: Layout-Grid2-Alt
        ti-layout-column4-alt: Layout-Column4-Alt
        ti-layout-column3-alt: Layout-Column3-Alt
        ti-layout-column2-alt: Layout-Column2-Alt
        ti-instagram: Instagram
        ti-google: Google
        ti-github: Github
        ti-flickr: Flickr
        ti-facebook: Facebook
        ti-dropbox: Dropbox
        ti-dribbble: Dribbble
        ti-apple: Apple
        ti-android: Android
        ti-save: Save
        ti-save-alt: Save-Alt
        ti-yahoo: Yahoo
        ti-wordpress: Wordpress
        ti-vimeo-alt: Vimeo-Alt
        ti-twitter-alt: Twitter-Alt
        ti-tumblr-alt: Tumblr-Alt
        ti-trello: Trello
        ti-stack-overflow: Stack-Overflow
        ti-soundcloud: Soundcloud
        ti-sharethis: Sharethis
        ti-sharethis-alt: Sharethis-Alt
        ti-reddit: Reddit
        ti-pinterest-alt: Pinterest-Alt
        ti-microsoft-alt: Microsoft-Alt
        ti-linux: Linux
        ti-jsfiddle: Jsfiddle
        ti-joomla: Joomla
        ti-html5: Html5
        ti-flickr-alt: Flickr-Alt
        ti-email: Email
        ti-drupal: Drupal
        ti-dropbox-alt: Dropbox-Alt
        ti-css3: Css3
        ti-rss: Rss
        ti-rss-alt: Rss-Alt