baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Megakit"
Paginate = 20
PaginatePath = "/"
summaryLength = 10

[taxonomies]
category = "categories"

[permalinks]
posts = ":section/:year/:month/:day/:title/"

[module]
replacements = "local/component-library -> ../component-library"

[[module.imports]]
path = 'local/component-library'

[[module.imports]]
path = 'github.com/cloudcannon/bookshop/hugo/v3'