[component]
structures = ["content_blocks"]
label = "CTA Mini"
description = "Mini CTA block"
icon = "pending"
tags = []

[props]
preheading = "For every type business"
heading = "Entrust Your Project to Our Best Team of Professionals"
[props.button]
text = "Contact"
url = "/contact/"
